services:
  postgres:
    image: postgres:16-alpine
    container_name: travelshield-db
    environment:
      POSTGRES_USER: travelshield_app
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: travelshield
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travelshield_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - travelshield-network

  # # Опционально: pgAdmin для визуального управления БД
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: travelshield-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@travelshield.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - travelshield-network

volumes:
  postgres_data:
    driver: local

networks:
  travelshield-network:
    driver: bridge